

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/mia
#    username: root
#    password: root

spring:
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:ponto
    username: sa
  h2:
    console:
      enabled: false
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    
    
server:
  error:
    include-stacktrace: never
    
api:
  security:
    token:
      secret: ${JWT_SECRET:1234567890} # o que esta depois do : é um valor default
      
      